### ISSUE TITLE
Muerte a multidict

### ISSUE THREAD

**Issue by devedetti** [trifulca/panflix#2]
Hugo, tenemos que emparchar Sanic para que no use [multidict](https://github.com/aio-libs/multidict) (ta implementada en C)

``` python
Traceback (most recent call last):
  File "panflix_sanic.py", line 5, in <module>
    from sanic import Sanic
  File "/home/nachopro/desarrollo/panflix/dependencias/sanic/__init__.py", line 1, in <module>
    from sanic.app import Sanic
  File "/home/nachopro/desarrollo/panflix/dependencias/sanic/app.py", line 19, in <module>
    from sanic.handlers import ErrorHandler
  File "/home/nachopro/desarrollo/panflix/dependencias/sanic/handlers.py", line 18, in <module>
    from sanic.response import html, text
  File "/home/nachopro/desarrollo/panflix/dependencias/sanic/response.py", line 7, in <module>
    from multidict import CIMultiDict
ModuleNotFoundError: No module named 'multidict'
```

**Comment by hugoruscitti** [comment]
Grosoo!!
