### ISSUE TITLE
No se puede agregar httptools :(

### ISSUE THREAD

**Issue by devedetti** [trifulca/panflix#3]
[httptools](https://github.com/MagicStack/httptools/blob/master/README.md) compila bindings contra node!!! Dejame de joder!

``` python
Traceback (most recent call last):
  File "panflix_sanic.py", line 5, in <module>
    from sanic import Sanic
  File "/home/nachopro/desarrollo/panflix/dependencias/sanic/__init__.py", line 1, in <module>
    from sanic.app import Sanic
  File "/home/nachopro/desarrollo/panflix/dependencias/sanic/app.py", line 23, in <module>
    from sanic.server import HttpProtocol, Signal, serve, serve_multiple
  File "/home/nachopro/desarrollo/panflix/dependencias/sanic/server.py", line 13, in <module>
    from httptools import HttpRequestParser
ModuleNotFoundError: No module named 'httptools'
```

**Comment by devedetti** [comment]
Por ahora hice un `pip install --user httptools==0.0.11` pero la verdad que es una mierda :(

**Comment by hugoruscitti** [comment]
Al final pasamos todo a nodejs, así que este issue quedó medio obsoleto. Lo cierro.
